title: Edmonds Bakery 
email: edmondsbakery@comcast.net

description: Edmonds Bakery is a local bakery that focuses on creating donuts, pastries, and custom cakes. Open 7am to 4:30 pm.
### baseurl: bakery

sass:
 style: compressed
 
 
# Tracker
analytics: UA-120986760-1
### exclude the instructions / write-up in the README.md
exclude:
- README.md
